export { setAttribute } from './setAttribute'
export type { I_SetAttributeConfig } from './setAttribute'
export { setVisibility } from './visibility'
export type { I_SetVisibilityConfig, T_VisibilityValue } from './visibility'
export { setOpacity } from './opacity'
export type { I_SetOpacityConfig } from './opacity'
export { setDisplay } from './display'
export type { I_SetDisplayConfig } from './display'
export { setFill } from './fill'
export type { I_SetFillConfig } from './fill'
export { setStroke } from './stroke'
export type { I_SetStrokeConfig } from './stroke'
export { setStrokeWidth } from './strokeWidth'
export type { I_SetStrokeWidthConfig } from './strokeWidth'
export { setX } from './x'
export type { I_SetXConfig } from './x'
export { setY } from './y'
export type { I_SetYConfig } from './y'
export { setWidth } from './width'
export type { I_SetWidthConfig } from './width'
export { setHeight } from './height'
export type { I_SetHeightConfig } from './height'
export { setRx } from './rx'
export type { I_SetRxConfig } from './rx'
export { setRy } from './ry'
export type { I_SetRyConfig } from './ry'
export { setR } from './r'
export type { I_SetR_Config } from './r'
export { setCx } from './cx'
export type { I_SetCxConfig } from './cx'
export { setCy } from './cy'
export type { I_SetCyConfig } from './cy'
export { setHref } from './href'
export type { I_SetHrefConfig } from './href'
